package com.model;

/**
 * TJingpai generated by MyEclipse Persistence Tools
 */

public class TJingpai implements java.io.Serializable
{

	// Fields

	private Integer jingpaiId;

	private Integer jingpaiJiage;

	private Integer jingpaiObjfwId;

	private Integer jingpaiUserId;

	private String jingpaiShijian;

	private String del;
	
	private String jingpaiObjfwName;

	// Constructors

	/** default constructor */
	public TJingpai()
	{
	}

	/** full constructor */
	public TJingpai(Integer jingpaiJiage, Integer jingpaiObjfwId,
			Integer jingpaiUserId, String jingpaiShijian, String del)
	{
		this.jingpaiJiage = jingpaiJiage;
		this.jingpaiObjfwId = jingpaiObjfwId;
		this.jingpaiUserId = jingpaiUserId;
		this.jingpaiShijian = jingpaiShijian;
		this.del = del;
	}

	// Property accessors

	public Integer getJingpaiId()
	{
		return this.jingpaiId;
	}

	public void setJingpaiId(Integer jingpaiId)
	{
		this.jingpaiId = jingpaiId;
	}

	public Integer getJingpaiJiage()
	{
		return this.jingpaiJiage;
	}

	public void setJingpaiJiage(Integer jingpaiJiage)
	{
		this.jingpaiJiage = jingpaiJiage;
	}

	public Integer getJingpaiObjfwId()
	{
		return this.jingpaiObjfwId;
	}

	public void setJingpaiObjfwId(Integer jingpaiObjfwId)
	{
		this.jingpaiObjfwId = jingpaiObjfwId;
	}

	public Integer getJingpaiUserId()
	{
		return this.jingpaiUserId;
	}

	public void setJingpaiUserId(Integer jingpaiUserId)
	{
		this.jingpaiUserId = jingpaiUserId;
	}

	public String getJingpaiShijian()
	{
		return this.jingpaiShijian;
	}

	public void setJingpaiShijian(String jingpaiShijian)
	{
		this.jingpaiShijian = jingpaiShijian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getJingpaiObjfwName()
	{
		return jingpaiObjfwName;
	}

	public void setJingpaiObjfwName(String jingpaiObjfwName)
	{
		this.jingpaiObjfwName = jingpaiObjfwName;
	}

}