package com.model;

/**
 * TObjfw generated by MyEclipse Persistence Tools
 */

public class TObjfw implements java.io.Serializable
{

	// Fields

	private Integer objfwId;

	private String objfwName;
	
	private String objfwArea;

	private String objfwMiaoshu;

	private String fujian;

	private Integer objfwDijia;

	private Integer objfwCatelogId;

	private Integer objfwUserId;
	
	private String objfwShijian;

	private String objfwDel;
	
	private String shenheFlag;//0：没有审核的，1：审核通过

	// Constructors

	public String getShenheFlag() {
		return shenheFlag;
	}

	public void setShenheFlag(String shenheFlag) {
		this.shenheFlag = shenheFlag;
	}

	/** default constructor */
	public TObjfw()
	{
	}

	/** full constructor */
	public TObjfw(String objfwName, String objfwArea,String objfwMiaoshu,
			Integer objfwDijia, Integer objfwCatelogId, Integer objfwUserId,
			String objfwDel,String shenheFlag)
	{
		this.objfwName = objfwName;
		this.objfwArea = objfwArea;
		this.objfwMiaoshu = objfwMiaoshu;
		this.objfwDijia = objfwDijia;
		this.objfwCatelogId = objfwCatelogId;
		this.objfwUserId = objfwUserId;
		this.objfwDel = objfwDel;
		this.shenheFlag = shenheFlag;
	}

	// Property accessors

	public Integer getObjfwId()
	{
		return this.objfwId;
	}

	public String getObjfwShijian()
	{
		return objfwShijian;
	}

	public void setObjfwShijian(String objfwShijian)
	{
		this.objfwShijian = objfwShijian;
	}

	public void setObjfwId(Integer objfwId)
	{
		this.objfwId = objfwId;
	}

	public String getObjfwName()
	{
		return this.objfwName;
	}

	public void setObjfwName(String objfwName)
	{
		this.objfwName = objfwName;
	}

	public String getObjfwArea()
	{
		return this.objfwArea;
	}

	public void setObjfwArea(String objfwArea)
	{
		this.objfwArea = objfwArea;
	}
	
	public String getObjfwMiaoshu()
	{
		return this.objfwMiaoshu;
	}

	public void setObjfwMiaoshu(String objfwMiaoshu)
	{
		this.objfwMiaoshu = objfwMiaoshu;
	}


	public Integer getObjfwDijia()
	{
		return this.objfwDijia;
	}

	public void setObjfwDijia(Integer objfwDijia)
	{
		this.objfwDijia = objfwDijia;
	}

	public Integer getObjfwCatelogId()
	{
		return this.objfwCatelogId;
	}

	public void setObjfwCatelogId(Integer objfwCatelogId)
	{
		this.objfwCatelogId = objfwCatelogId;
	}

	public Integer getObjfwUserId()
	{
		return this.objfwUserId;
	}

	public void setObjfwUserId(Integer objfwUserId)
	{
		this.objfwUserId = objfwUserId;
	}

	public String getObjfwDel()
	{
		return this.objfwDel;
	}

	public void setObjfwDel(String objfwDel)
	{
		this.objfwDel = objfwDel;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

}