package com.model;

/**
 * TPinglun generated by MyEclipse Persistence Tools
 */

public class TPinglun implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer objfwId;

	private String content;

	private String shijian;

	// Constructors

	/** default constructor */
	public TPinglun()
	{
	}

	/** full constructor */
	public TPinglun(Integer objfwId, String content, String shijian)
	{
		this.objfwId = objfwId;
		this.content = content;
		this.shijian = shijian;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getObjfwId()
	{
		return this.objfwId;
	}

	public void setObjfwId(Integer objfwId)
	{
		this.objfwId = objfwId;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

}